### ISSUE TITLE
Payment fake 결제 구현

### ISSUE THREAD

**Issue by JisuNa** [f-lab-edu/Starlucks#11]

**Comment by f-lab-bright** [comment]
다양한 pg사들을 수용할 수 있으려면 어떻게 추상화하면 좋을까요??
pg사 별로 제공되는 정보들에도 차이가 있을텐데, 어떻게 관리하고 저장하면 좋을까요?

**Comment by gyhcom** [comment]
팩토리 패턴으로 구현된 소스 확인했습니다.

필요할때마다 추가 Pg사 서브 클래스를 만들어(TossPaymentStraegy) 
Payment를 상속받아  서브클래스에서 getName을 가져와 어떤 pg사인지 확인하네요.

현재는 개발단계이기 때문에 TossPayment 만 있어서 그렇지만
추후에는 각 pg사마다 repository.save를 각각하기 보다는 공통으로 빼서 진행하면 좋지 않을까 싶습니다.
고생하셨습니다.

잘 봤습니다 . 👍
